spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/notificationdb
  kafka:
    bootstrap-servers: kafka:29092
  mail:
    host: maildev

grpc:
  client:
    user-service:
      host: user-service
      port: 9081
      negotiationType: plaintext
