spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: m.onat.65@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

application:
  notification:
    simulate-email: false
    from-email: m.onat.65@gmail.com
