apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: apps
spec:
  selector:
    app: inventory-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: grpc
      port: 9083
      targetPort: 9083
