apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: apps
spec:
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8086
      targetPort: 8086
    - name: grpc
      port: 9086
      targetPort: 9086
