apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: logging
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
      gelf {
        port => 12201
      }
    }

    filter {
      if [message] =~ /^\{.*\}$/ {
        json {
          source => "message"
          target => "log"
        }
        if [log][timestamp] {
          date {
            match => ["[log][timestamp]", "ISO8601"]
            target => "@timestamp"
          }
        }
        mutate {
          add_field => {
            "service_name" => "%{[log][logger_name]}"
            "log_level"    => "%{[log][level]}"
          }
        }
      }
      if [kubernetes][pod][name] {
        mutate {
          add_field => { "service" => "%{[kubernetes][pod][name]}" }
        }
      }
      if [message] =~ /Exception|Error/ {
        mutate { add_tag => ["error"] }
      }
    }

    output {
      elasticsearch {
        hosts         => ["http://elasticsearch-master.logging.svc.cluster.local:9200"]
        index         => "microservices-logs-%{+YYYY.MM.dd}"
        template_name => "microservices"
        template_overwrite => true
      }
    }
